### ISSUE TITLE
Add better inotify support.

### ISSUE THREAD

**Issue by mmerickel** [Pylons/hupper#21]
Watchdog is basically dead and unmaintained and has caused a couple irritating bugs for people such as https://github.com/Pylons/pyramid/issues/2920

One option is to fork watchdog into watchdog-lite that focuses on our simplified use case and doesn't ship with the cli runner that depends on pyyaml (if we did this I would consider adding it as a direct dependency of hupper). Another is to evaluate less cross-platform options such as recommending installing inotify on some systems, etc. This would be a last resort, however, because watchdog already does a pretty good job.

**Comment by piotr-dobrogost** [comment]
For clarity, _Watchdog_ mentioned in the description of this issue refers to https://github.com/gorakhargosh/watchdog
