### ISSUE TITLE
Cannot catch new package install until manual reload

### ISSUE THREAD

**Issue by a3kov** [Pylons/hupper#24]
I don't know if its a bug, but it could be.

1. start `pserve --reload`
2. run `pip install -e newpackage`
3. pserve does not reload
4. add `import newpackage` to the project code
5. pserve reloads, but gets `ImportError`
6. stop pserve; start pserve. Now everything is fine

Looks like some package cache (?) could be involved, which is only cleared on fresh start

**Comment by mmerickel** [comment]
I imagine this will be fixed with #23 if you want to try it out.

**Comment by mmerickel** [comment]
To be clear there's no expectation that installing a new package will trigger a reload. Hupper only watches modules that are actually being used so you'd need to import the package and save to trigger the reload... it's only the final import error I'm worried about.

**Comment by mmerickel** [comment]
I just released 0.5 so please confirm this is no longer an issue.

**Comment by a3kov** [comment]
Confirming
