### ISSUE TITLE
stop squashing certain inotify limit errors

### ISSUE THREAD

**Issue by mmerickel** [Pylons/hupper#26]
See https://github.com/Pylons/pyramid/issues/2920

If we can figure out what error is being raised in `watchdog.py` when the inotify limit is reached we can stop squashing it. It would be useful output for a user.

**Comment by slav0nic** [comment]
watchdog raises general `OSError` https://github.com/gorakhargosh/watchdog/blob/v0.8.3/src/watchdog/observers/inotify_c.py#L403-L404

**Comment by mmerickel** [comment]
gross

I think the best solution might be to log a warning when these errors are received but continue to prevent them from crashing the monitor.

**Comment by slav0nic** [comment]
maybe be will good idea skip `__pycache__` directories (it doesn't helped in my project, but at least halved monitored directories)?
Also `Observer.shedule` have `recursive` keyword, but looks like it have this bug too :/ https://github.com/gorakhargosh/watchdog/blob/v0.8.3/src/watchdog/observers/api.py#L258

**Comment by mmerickel** [comment]
hupper logs an error now when it receives these errors
