### ISSUE TITLE
gevent.monkey.patch_all() support

### ISSUE THREAD

**Issue by dmartin-gh** [Pylons/hupper#36]
Our product runs in a gevent.pywsi+Pyramid server with `monkey.patch_all()` enabled. For the most part this works great. However, the `--reload` flag to `pserve` does not work out of the box. Our application fails to start up entirely and source file changes do not trigger a reload. I did manage to get it working, but it required some tweaks. I will detail what our solution was in case you want to add support for this use case or if anyone else out there is curious how to get this working. 

I created a `pserve` wrapper command called `gserve`:

```python
#!/usr/bin/python3.6
from gevent import monkey; monkey.patch_all()
from ourproduct import monkey; monkey.patch_hupper()
from pyramid.scripts.pserve import main; main()
```

This ensures that gevent has a chance to patch everything before hupper or pyramid has a chance to run. This wrapper script serves as a drop-in replacement for `pserve`.

The `ourproduct.monkey.patch_hupper()` function looks like this:

```python
def patch_hupper():
    # Patch hupper to work with gevent so gserve --reload works!
    from gevent import os
    from hupper.ipc import Connection
    from mock import patch
    _recv_packet = Connection._recv_packet
    @patch('os.read', side_effect=os.tp_read)
    def _patched_recv_packet(self, tp_read):
        return _recv_packet(self)
    Connection._recv_packet = _patched_recv_packet
```

gevent does not patch `os.read` or `os.write` (see [gevent.os](http://www.gevent.org/api/gevent.os.html)). I use `mock.patch` to ensure my replacement of `os.read` only affects the `_recv_packet` method. I tried `gevent.os.nb_read` first, which did not work, then switched to `gevent.os.tp_read`.

This was enough for hupper to spawn the server in a subprocess and for basic reload functionality to work. However, the server spawned in the subprocess was no longer gevent-patched, as it is not spawned using `gserve`. This prevented the server from starting up completely as many calls were now blocking that weren't before.

The `hupper.ipc` module starts a new interpreter and then uses `hupper.ipc.spawn_main` to import and run a python function (in this case `pyramid.scripts.pserve.main`). To make sure the subprocess runs both `patch_all()` and `patch_hupper()`, I made the following change to `hupper/ipc.py`:

```patch
--- hupper/ipc.py	2018-06-14 01:25:35.000000000 -0500
+++ hupper/ipc.py	2018-06-21 14:14:56.226000000 -0500
@@ -250,7 +250,7 @@


 def get_command_line(**kwds):
-    prog = 'from hupper.ipc import spawn_main; spawn_main(%s)'
+    prog = 'from gevent import monkey; monkey.patch_all(); from ourproduct import monkey; monkey.patch_hupper(); from hupper.ipc import spawn_main; spawn_main(%s)'
     prog %= ', '.join('%s=%r' % item for item in kwds.items())
     opts = args_from_interpreter_flags()
     args = [sys.executable] + opts + ['-c', prog]
```

After that hack was in place, the server remained patched after being spawned in a subprocess by hupper and would successfully reload after source changes. We're now running with that patched version of hupper, but an official solution would be nice.

One possible fix would be for us to supply hupper with code that we want executed before anything else in the subprocess. We would then be able to give it the patch statements we would like executed and it would blindly execute them prior to `from hupper.ipc import spawn_main; spawn_main(%s)`. 

Another fix might be to spawn the server in yet another subprocess using the exact `sys.argv` used originally. This would cause the server to be spawned again using the `gserve` wrapper instead of hupper being provided with a module entry point (i.e. `pyramid.scripts.pserve.main`) to load and run, which ends up skipping `gserve` entirely.

Thoughts and comments appreciated! Hopefully this at least helps some people using `patch_all()` also utilize the `--reload` flag to `pserve`.

**Comment by digitalresistor** [comment]
Instead of going through `pserve` I would recommend creating a small wrapper script that does the monkeypatching/setting up the appropriate context using `plaster` and then just call `hupper` directly.

For example, here is how pypa/warehouse uses `hupper` with `gunicorn`:

```
hupper -m gunicorn.app.wsgiapp -b 0.0.0.0:8000 -c gunicorn-cabotage.conf warehouse.wsgi:application
```

Monkeypatching `hupper` itself seems like a terrible idea (especially with a lot of the magic it does behind the scenes), and this would allow your sub-process to be appropriately monkey patched however you'd like.
