### ISSUE TITLE
Can I register callbacks for other purposes?

### ISSUE THREAD

**Issue by pauleveritt** [Pylons/hupper#45]
I have a Pyramid project where content is authored as Markdown on disk. I want treat `pserve` as an authoring server: you edit Markdown content, the browser reloads.

Thus I need something that watches for a recursive glob and hands changes to a callback I register. I saw the [WatchmanFileMonitor](https://docs.pylonsproject.org/projects/hupper/en/latest/api.html#hupper.watchman.WatchmanFileMonitor) discusses a callback. But I'm not sure:

- How in Pyramid to get the in-use hupper to make a registration
- Will it replace the callback already in use

On a related note, I see the callback is called with each file in a changeset. Does this mean, when a bunch of files are copied in, a bunch of callbacks are fired? (Would be nice to batch things.)

**Comment by mmerickel** [comment]
Hupper is a process reloader and I'm not sure the architecture you are describing fits into how hupper works. For example it cannot trigger a browser reload. It runs the file monitor in a master process and just uses the changed files to kill the child process and restart it. The child process can tell it to monitor more files via `reloader.watch_files(...)`.

> * How in Pyramid to get the in-use hupper to make a registration

You can use `reloader.watch_files(...)` to tell hupper to restart the process if these files change.

> * Will it replace the callback already in use

The callback is supplied by hupper and is used to restart the child process. There is no api to replace it.

> On a related note, I see the callback is called with each file in a changeset. Does this mean, when a bunch of files are copied in, a bunch of callbacks are fired? (Would be nice to batch things.)

Yeah right now the monitors only return a path at a time.

It seems to me you might want to create and use your own file monitor directly but that you do not really want all of what hupper provides. Am I misunderstanding?

**Comment by pauleveritt** [comment]
The browser reload isn't important to this discussion. I planned to use SSE so the server could tell the browser. What was attractive about doing this in hupper:

- You've already figured out integration with watchman as well as polling
- You've already figured out integration into Pyramid

But:

- The `HUP` in hupper is clearly about restart, thus this request is abuse :)
- I don't think you're actually integrated into Pyramid..I think hupper is a separate process

**Comment by mmerickel** [comment]
@pauleveritt you're right, hupper is maintaining a process tree like the diagram below. Pyramid can use the proxy to communicate with the reloader/file monitor but when a file is changed the pyramid process is killed. This enables hupper to not fully die when the pyramid process fails to start up - it can wait for file changes and keep trying to start again. :-)

That being said you're welcome to use the WatchmanFileMonitor directly, or copy it out - it's intentionally pretty standalone in implementation.

```
+---------------------------------------------+
|  parent process                             |
|                                             |
|      +------------+       +---------------+ |
|      |  reloader  |<------| file monitor  | |
|      +------------+       +---------------+ |
|             ^                               |
|             |                               |
+-------------+-------------------------------+
              |                                
+-------------+-------------------------------+
|             |                               |
|             v                               |
|    +----------------+       +------------+  |
|    | reloader proxy |<------|  pyramid   |  |
|    +----------------+       +------------+  |
|                                             |
|  child process                              |
+---------------------------------------------+
```
