### ISSUE TITLE
Hupper fails to reload app cleanly on Docker Compose environments

### ISSUE THREAD

**Issue by yeraydiazdiaz** [Pylons/hupper#54]
Hello all, first off thanks for hupper 🌟 

The warehouse team uses hupper in our development stack but [recently](https://github.com/pypa/warehouse/issues/6578) we started noticing the it failed to restart on code changes. I believe this is because we invoke hupper in a Docker Compose environment causes the `input` call to fail with an EOF.

We've worked around it by pinning the hupper version to 1.7 but ideally there'd be a CLI option to prevent reading from stdin. Would that be acceptable?

**Comment by mmerickel** [comment]
Would it be enough to just make hupper robust to that feature not working instead of adding a flag? I think we could just handle issues with stdin in the `wait_main` and not support the pressing Enter functionality in that case.

I assume the current behavior is that hupper gets in a reloading loop that just keeps trying to restart your app?

**Comment by yeraydiazdiaz** [comment]
Sure, I guess I jumped the gun suggesting a solution rather than explaining the problem.

The symptom is that hupper tries to restart the application but it fails because the previous app did not exit and is still bound to the port. Here's a copy of the Docker logs:

```
web_1            | [2019-09-04 09:31:05 +0000] [16] [INFO] Worker exiting (pid: 16)
web_1            | Server did not exit, forcefully killing.
web_1            | Starting monitor for PID 17.
web_1            | {"logger": "raven.base.Client", "level": "INFO", "event": "Raven is not configured (logging is disabled). Please see the documentation for more information.", "thread": 140079147017984}
web_1            | [2019-09-04 09:31:31 +0000] [17] [INFO] Starting gunicorn 19.9.0
web_1            | [2019-09-04 09:31:31 +0000] [17] [ERROR] Connection in use: ('0.0.0.0', 8000)
web_1            | [2019-09-04 09:31:31 +0000] [17] [ERROR] Retrying in 1 second.
web_1            | [2019-09-04 09:31:32 +0000] [17] [ERROR] Connection in use: ('0.0.0.0', 8000)
web_1            | [2019-09-04 09:31:32 +0000] [17] [ERROR] Retrying in 1 second.
web_1            | [2019-09-04 09:31:33 +0000] [17] [ERROR] Connection in use: ('0.0.0.0', 8000)
web_1            | [2019-09-04 09:31:33 +0000] [17] [ERROR] Retrying in 1 second.
web_1            | [2019-09-04 09:31:34 +0000] [17] [ERROR] Connection in use: ('0.0.0.0', 8000)
web_1            | [2019-09-04 09:31:34 +0000] [17] [ERROR] Retrying in 1 second.
web_1            | [2019-09-04 09:31:35 +0000] [17] [ERROR] Connection in use: ('0.0.0.0', 8000)
web_1            | [2019-09-04 09:31:35 +0000] [17] [ERROR] Retrying in 1 second.
web_1            | [2019-09-04 09:31:36 +0000] [17] [ERROR] Can't connect to ('0.0.0.0', 8000)
web_1            | Press ENTER or change a file to reload.
web_1            | Traceback (most recent call last):
web_1            |   File "<string>", line 1, in <module>
web_1            |   File "/opt/warehouse/lib/python3.7/site-packages/hupper/ipc.py", line 318, in spawn_main
web_1            |     func(**kwargs)
web_1            |   File "/opt/warehouse/lib/python3.7/site-packages/hupper/worker.py", line 263, in worker_main
web_1            |     func(*spec_args, **spec_kwargs)
web_1            |   File "/opt/warehouse/lib/python3.7/site-packages/hupper/reloader.py", line 285, in wait_main
web_1            |     input('')
web_1            | EOFError: EOF when reading a line
web_1            | Starting monitor for PID 30.

... repeats endlessly...
```

The specific hupper invocation we use is in the `docker-compose.yml`: https://github.com/pypa/warehouse/blob/master/docker-compose.yml#L48

**Comment by digitalresistor** [comment]
The issue here is that hupper is forcefully killing the gunicorn server and gunicorn is not tearing that down fast enough.

Not sure if we have a knob to control how long teardown is allowed to take. You should also try to figure out why gunicorn isn't killing itself in time.

**Comment by digitalresistor** [comment]
https://github.com/Pylons/hupper/blob/21c85d44595058eba897cd9b929292b1bc062fc9/CHANGES.rst#16-2019-03-06

shutdown_interval is the configuration variable you'll want to change. It's set 1 second right now, so you may want to try updating that value to something a little higher.

**Comment by mmerickel** [comment]
hupper has a `shutdown_interval` [1] which is available in the api but not via the cli right now (would accept a pr to add it) - this controls how long to wait after sending a SIGTERM to the process, so if gunicorn deals with that gracefully then this would be the parameter to look at.

[1] https://docs.pylonsproject.org/projects/hupper/en/latest/api.html#hupper.start_reloader

**Comment by mmerickel** [comment]
https://github.com/pypa/pip/blob/53ee380d95b49a66c87eea6bda41b1c1fef7c600/src/pip/_internal/utils/misc.py#L866-L870 looks worth using for the original request as well. Linking here as a reminder for when I get to this. Sorry for the delay!
