### ISSUE TITLE
Broken when watchman 2022.01.17.00_0 is installed

### ISSUE THREAD

**Issue by icemac** [Pylons/hupper#74]
What I did:

* Using `hupper = 1.10.3` on MacOS 12.3.1 -> works like a charm
* Afterwards installed `watchman == 2022.01.17.00_0` using MacPorts.

What happened:

* Hupper no longer restarts the process on file changes.
* Stopping the hupper using ^C no longer work, i have to force kill it.
* Sorry, no log messages nor anything else which could guide to the source of the problem. It just hangs and does nothing.
* Uninstalling `watchman` fixed the problem, so it seems to be the reason behind.

**Comment by mmerickel** [comment]
I haven't run into issues with the later watchman versions. For example it's working for me with 2022.10.24 and just upgraded to 2022.10.31 and that one is also fine. Can you confirm if this is still an issue?

**Comment by icemac** [comment]
I tested against version `2022.08.22.00_0` of `watchman` and it works, so closing the issue.

**Comment by icemac** [comment]
Thank you for looking into the issue.
