### ISSUE TITLE
Can the exit code be changed?

### ISSUE THREAD

**Issue by npalmius** [Pylons/hupper#80]
I'm using `hupper` to run a Flask server in a VS Code devcontainer with debugging (using `debugpy`). Generally all is working well while the server is running - reloading is working perfectly, as is debugging.

The only problem is that the way VS Code runs the app with debugging means that `hupper` is run within the debugger. Usually this doesn't cause any problems, but when the process ends (e.g. with with ctrl-c) `hupper` exits with `sys.exit(1)`. The VS Code debugger then picks this up as an unhandled `SystemExit` exception.

Is there a reason to return a non-zero exit code? Could this be changed to a `0` success exit code? Conceptually I think the process has ended normally so `0` would be an acceptable exit code anyway.

**Comment by mmerickel** [comment]
I would accept a pr to change the exit code of the parent process.
