### ISSUE TITLE
Consider allowing the child process to exit the parent process

### ISSUE THREAD

**Issue by joshuafcole** [Pylons/hupper#86]
First off, thanks for hupper!

My usecase is to re-run a test suite each time I make a change to my project. I'm using hupper rather than an off the shelf solution like pytest-watcher because I wanted to wrap the test runner in a little repl that allows interacting with test filtering and allows interrogating the results.

When someone pressed ^C or types quit in the repl, I'd like to tell the monitoring proces to also exit, but I couldn't find any way to do that (short of hijacking the proxy's pipe to send an unrecognized message anyway, but that seems... inelegant). 

Would you consider adding a new proxy command, `exit()` (or perhaps `exit(code)` for this purpose?

If you think the feature is worthwhile but don't have time to add it yourself, I'd be happy to contribute.

Thanks for your consideration!
Josh

**Comment by mmerickel** [comment]
Interesting. Normally the ctrl-C is sent to all processes in the Unix process group so the monitor will see it and cleanup (start a shutdown timer before sending a SIGKILL to your repl). What scenario are you in that that isn’t happening?

Regardless I don’t see a problem with implementing a command similar to reloader.watch_files to trigger a full shutdown. Just make it clear somehow in naming that the method is killing everything - not just the child but the monitor process as well.

**Comment by joshuafcole** [comment]
I'm using prompt_toolkit, if I get some time I'll try to put together a
minimal repro to see if that might be related.

RE: also implementing an exit/shutdown command, it'd certainly be nice
if my repl could trigger it directly instead of trying to raise a SIGINT on
itself, but I could certainly live without it if I can figure out what's
blocking the former.

**Comment by mmerickel** [comment]
Yeah with `hupper.get_reloader().graceful_shutdown()` or something it'd send a message to the monitor, which would trigger a graceful shutdown. The monitor already has good support for a graceful shutdown (currently only triggered via a SIGINT to the monitor), in which it will wait shutdown_interval seconds, then send a SIGKILL to the child process, and then exit itself as well.

**Comment by mmerickel** [comment]
My proposal is to add the new API here to the `ReloaderProxy` if that isn't clear: https://github.com/Pylons/hupper/blob/5fb92dd8bfdff161717ab008a3c3ecc3de0750e2/src/hupper/worker.py#L234-L243

**Comment by joshuafcole** [comment]
Yeah, I'm with you. If you'd prefer it as a contribution, just let me know
what you'd like the name to be and I'll get it taken care of.

**Comment by mmerickel** [comment]
I would not be upset if you wanted to take it! :-)

**Comment by joshuafcole** [comment]
Please feel free if it's more convenient for you! Just don't want to
request something without offering some of my time in return.

**Comment by mmerickel** [comment]
I got a little carried away and went ahead and added it in #88. Very simple little feature. I hope it's helpful.

**Comment by joshuafcole** [comment]
Thanks, I really appreciate it!
