### ISSUE TITLE
Double license

### ISSUE THREAD

**Issue by lucasgonze** [Pylons/hupper#89]
# Problem

The cc-by-nc-sa-3.0-us license on the docs subdirectory is much less permissive than the MIT license on everything else. As far as I can tell the license on the docs applies to any usage of hupper, so the real top-level license is not MIT but MIT AND cc-by-nc-sa-3.0-us 

# Solution

Pick a license and stick to it.

# Context

Dual-licensing is usually one or the other, pick the one you like.  In this case there are two licenses on pretty much the same code.

**Comment by mmerickel** [comment]
It's incorrect to say that the license on the docs applies to the usage of hupper. It only applies to modifying/distributing of the documentation of the project.

I appreciate the perspective you're bringing but no one else has brought this up on many repos that I have used and IANAL so I have no intention to change this at this time without further evidence from some other sources that there's actually an issue here. You are the first person to bring it up on the repos I maintain and it's not enough for me to act on. Thank you though.

**Comment by lucasgonze** [comment]
Unless the documentation is uncoupled from the the rest of the project, it must be redistributed in any situation where the rest of the code is redistributed. The license that applies to the documentation is X. The license that applies to the rest is Y. Therefore compliance uses the terms of both X and Y.

**Comment by mmerickel** [comment]
The docs are not distributed in the wheels. Only in the sdist, source repo and what’s available on RTD (which doesn’t include the code). 

The docs are a separate entity from the code as the contributors agreement calls out.

**Comment by merwok** [comment]
This means that Debian won’t be able to distribute the docs 😐
https://lists.debian.org/debian-python/2026/03/msg00038.html

**Comment by mmerickel** [comment]
To my knowledge the same situation exists with pyramid. I haven’t seen that flagged as an issue?

**Comment by merwok** [comment]
Pyramid is not in Debian

**Comment by mmerickel** [comment]
huh TIL, I'm pretty certain it was at one point but good to know

**Comment by mmerickel** [comment]
Can't they just package hupper vs hupper-docs as different licenses?

**Comment by merwok** [comment]
I think the issue is that the non-commercial clause makes the work not free per Debian Free Software Guidelines.

**Comment by digitalresistor** [comment]
https://tracker.debian.org/pkg/python-pyramid

**Comment by merwok** [comment]
Yep, docs are excluded: https://salsa.debian.org/python-team/packages/python-pyramid/-/blob/debian/master/debian/README.source?ref_type=heads
